project:
  type: website
  output-dir: docs

website:
  title: "Semestre"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
        
      - text: No paramétrica
        menu: 
          - text: Capitulo 1
            href: capitulos/np/np1.qmd
          - text: Capitulo 2
            href: capitulos/np/np1.qmd 
            
      - text: Series de tiempo
        menu: 
          - text: Capitulo 1
            href: capitulos/st/st1.qmd
          - text: Capitulo 2
            href: capitulos/st/st1.qmd 
            
      - text: Bases de datos
        menu: 
          - text: GitHub
            href: capitulos/bd/bd1.qmd
          - text: aa
            href: capitulos/bd/bd1.qmd 

      - text: Complementos
        menu: 
          - text: GitHub
            href: capitulos/complementos/github.qmd
          - text: Capitulo 2
            href: capitulos/complementos/github.qmd       
    right: 
      - text: GitHub
        icon: github
        href: https://github.com/C-Mario/Semestre2023-2
        target: _blank
    logo: images/logo2.png
  back-to-top-navigation: true
  

format:
  html:
    include-in-header: _macros.tex
    theme: celula.scss
    toc: true
    code-line-numbers: true
    code-copy: hover
    grid: 
      body-width: 1200px
      content-mode: slim
      margin-width: 300px
      
editor: visual